INSERT INTO "public"."services" ("id", "category_key", "category_label", "name", "description", "price", "enabled", "show_in_web", "sort_order") VALUES 
(1, 'cert', 'Pramaan Patra (Certificates)', 'Mool Niwas (Domicile)', 'Niwas praman patra', 250.00, 1, 1, 0), 
(2, 'cert', 'Pramaan Patra (Certificates)', 'Jati Pramaan (Caste SC/ST/OBC)', 'Jati praman patra', 30.00, 1, 1, 1), 
(3, 'cert', 'Pramaan Patra (Certificates)', 'Aay Pramaan (Income)', 'Aay praman patra', 30.00, 1, 1, 2), 
(4, 'cert', 'Pramaan Patra (Certificates)', 'Janma/Mrityu (Birth/Death)', 'Janm/mrityu praman', 20.00, 1, 1, 3), 
(5, 'cert', 'Pramaan Patra (Certificates)', 'Vivah Panjiyan (Marriage)', 'Vivah panjiyan', 50.00, 1, 1, 4), 
(6, 'cert', 'Pramaan Patra (Certificates)', 'Charitra Pramaan (Character)', 'Charitra praman patra', 30.00, 1, 1, 5), 
(7, 'cert', 'Pramaan Patra (Certificates)', 'Minority Certificate', 'Alpasankhyak praman patra', 30.00, 1, 1, 6), 
(8, 'cert', 'Pramaan Patra (Certificates)', 'EWS Certificate', 'EWS praman pratra', 30.00, 1, 1, 7), 
(9, 'id', 'Pehchan (IDs & Updates)', 'Aadhar Card (New/Update)', 'Aadhar naam/address update', 50.00, 1, 1, 8), 
(10, 'id', 'Pehchan (IDs & Updates)', 'Jan Aadhar (New/Update)', 'Jan Aadhar card', 0.00, 1, 1, 9), 
(11, 'id', 'Pehchan (IDs & Updates)', 'PAN Card (New/Correction)', 'Naye PAN ke liye apply', 110.00, 1, 1, 10), 
(12, 'id', 'Pehchan (IDs & Updates)', 'Voter ID (New/Correction)', 'Voter ID banwao ya sudhar', 0.00, 1, 1, 11), 
(13, 'id', 'Pehchan (IDs & Updates)', 'PVC Aadhar Card Print', 'PVC Aadhar card print', 50.00, 1, 1, 12), 
(14, 'id', 'Pehchan (IDs & Updates)', 'SSO ID Creation', 'Rajasthan SSO ID banao', 0.00, 1, 1, 13), 
(15, 'id', 'Pehchan (IDs & Updates)', 'Ration Card Correction', 'Ration card mein sudhar', 0.00, 1, 1, 14), 
(16, 'id', 'Pehchan (IDs & Updates)', 'Passport Apply', 'Passport ke liye apply', 1500.00, 1, 1, 15), 
(17, 'bills', 'Bills, Recharge & Taxes', 'Bijli Bill (Electricity)', 'Bijli bill payment', 0.00, 1, 1, 16), 
(18, 'bills', 'Bills, Recharge & Taxes', 'Pani Bill (Water)', 'Pani bill payment', 0.00, 1, 1, 17), 
(19, 'bills', 'Bills, Recharge & Taxes', 'Mobile/DTH Recharge', 'Mobile ya DTH recharge', 0.00, 1, 1, 18), 
(20, 'bills', 'Bills, Recharge & Taxes', 'Gas Cylinder Booking', 'LPG cylinder booking', 0.00, 1, 1, 19), 
(21, 'bills', 'Bills, Recharge & Taxes', 'FASTag Recharge', 'FASTag recharge', 0.00, 1, 1, 20), 
(22, 'bills', 'Bills, Recharge & Taxes', 'ITR (Income Tax Return)', 'Income tax return file karo', 200.00, 1, 1, 21), 
(23, 'bills', 'Bills, Recharge & Taxes', 'CM Helpline Sikayat', 'CM helpline complaint', 0.00, 1, 1, 22), 
(24, 'bills', 'Bills, Recharge & Taxes', 'Traffic Challan Pay', 'Traffic challan payment', 0.00, 1, 1, 23), 
(25, 'forms', 'Siksha & Exams (Forms)', 'Govt. Job Form (RPSC/RSMSSB)', 'Sarkari naukri form', 100.00, 1, 1, 24), 
(26, 'forms', 'Siksha & Exams (Forms)', 'College Admission Form', 'College admission form', 50.00, 1, 1, 25), 
(27, 'forms', 'Siksha & Exams (Forms)', 'Scholarship (Chatravriti)', 'Chatravriti ke liye apply', 0.00, 1, 1, 26), 
(28, 'forms', 'Siksha & Exams (Forms)', 'RTE Form (Free Education)', 'RTE ke liye form', 0.00, 1, 1, 27), 
(29, 'forms', 'Siksha & Exams (Forms)', 'Gargi Puraskar Form', 'Gargi puraskar form', 0.00, 1, 1, 28), 
(30, 'forms', 'Siksha & Exams (Forms)', 'REET/CET/Police Form', 'REET, CET, Police form', 100.00, 1, 1, 29), 
(31, 'forms', 'Siksha & Exams (Forms)', 'Rojgar Panjiyan', 'Rachayment panjiyan', 0.00, 1, 1, 30), 
(32, 'forms', 'Siksha & Exams (Forms)', 'Berojgari Bhatta', 'Berojgari bhatta ke liye', 0.00, 1, 1, 31), 
(33, 'schemes', 'Yojana & Pension', 'Vridhavastha Pension', 'Budhape ki pension', 0.00, 1, 1, 32), 
(34, 'schemes', 'Yojana & Pension', 'Vidhwa Pension', 'Vidhwa pension', 0.00, 1, 1, 33), 
(35, 'schemes', 'Yojana & Pension', 'Viklang Pension', 'Viklang pension', 0.00, 1, 1, 34), 
(36, 'schemes', 'Yojana & Pension', 'Palanhar Yojana', 'Palanhar yojana form', 0.00, 1, 1, 35), 
(37, 'schemes', 'Yojana & Pension', 'Shramik/Labour Card', 'Shramik card banao', 0.00, 1, 1, 36), 
(38, 'schemes', 'Yojana & Pension', 'PM Awas Yojana', 'PM Awas yojana', 0.00, 1, 1, 37), 
(39, 'schemes', 'Yojana & Pension', 'PM Kisaan Samman Nidhi', 'PM Kisaan samman nidhi', 0.00, 1, 1, 38), 
(40, 'schemes', 'Yojana & Pension', 'Ayushman/Chiranjeevi Card', 'Ayushman card banao', 0.00, 1, 1, 39), 
(41, 'land_auto', 'Krishi, Khata & Vahan', 'Khasra/Jamabandi Nakal', 'Khasra/jamabandi nakal', 20.00, 1, 1, 40), 
(42, 'land_auto', 'Krishi, Khata & Vahan', 'Tarbandi Subsidy', 'Tarbandi subsidy', 0.00, 1, 1, 41), 
(43, 'land_auto', 'Krishi, Khata & Vahan', 'Fasal Bima (Crop Insurance)', 'Fasal bima', 0.00, 1, 1, 42), 
(44, 'land_auto', 'Krishi, Khata & Vahan', 'Krishi Yantra Subsidy', 'Krishi yantra subsidy', 0.00, 1, 1, 43), 
(45, 'land_auto', 'Krishi, Khata & Vahan', 'Driving License (DL)', 'DL banao ya renew karo', 200.00, 1, 1, 44), 
(46, 'land_auto', 'Krishi, Khata & Vahan', 'Vahan RC Print/Transfer', 'RC print ya transfer', 100.00, 1, 1, 45), 
(47, 'land_auto', 'Krishi, Khata & Vahan', 'Police Verification', 'Police verification', 50.00, 1, 1, 46), 
(48, 'land_auto', 'Krishi, Khata & Vahan', 'Hasiyat Pramaan (Solvency)', 'Hasiyat praman patra', 30.00, 1, 1, 47);